# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.nexus_pb2 as nexus__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusServiceStub(object):
    """NexusService handles all publisher and consumer operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEventStream = channel.unary_unary(
                '/nexus.NexusService/RegisterEventStream',
                request_serializer=nexus__pb2.RegisterEventStreamRequest.SerializeToString,
                response_deserializer=nexus__pb2.RegisterEventStreamResponse.FromString,
                _registered_method=True)
        self.RegisterFile = channel.unary_unary(
                '/nexus.NexusService/RegisterFile',
                request_serializer=nexus__pb2.RegisterFileRequest.SerializeToString,
                response_deserializer=nexus__pb2.RegisterFileResponse.FromString,
                _registered_method=True)
        self.RegisterDirectory = channel.unary_unary(
                '/nexus.NexusService/RegisterDirectory',
                request_serializer=nexus__pb2.RegisterDirectoryRequest.SerializeToString,
                response_deserializer=nexus__pb2.RegisterDirectoryResponse.FromString,
                _registered_method=True)
        self.RegisterDatabaseTable = channel.unary_unary(
                '/nexus.NexusService/RegisterDatabaseTable',
                request_serializer=nexus__pb2.RegisterDatabaseTableRequest.SerializeToString,
                response_deserializer=nexus__pb2.RegisterDatabaseTableResponse.FromString,
                _registered_method=True)
        self.StoreValue = channel.unary_unary(
                '/nexus.NexusService/StoreValue',
                request_serializer=nexus__pb2.StoreValueRequest.SerializeToString,
                response_deserializer=nexus__pb2.StoreValueResponse.FromString,
                _registered_method=True)
        self.DeletePath = channel.unary_unary(
                '/nexus.NexusService/DeletePath',
                request_serializer=nexus__pb2.DeletePathRequest.SerializeToString,
                response_deserializer=nexus__pb2.DeletePathResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/nexus.NexusService/Subscribe',
                request_serializer=nexus__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=nexus__pb2.Event.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/nexus.NexusService/GetNode',
                request_serializer=nexus__pb2.GetPathRequest.SerializeToString,
                response_deserializer=nexus__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/nexus.NexusService/GetChildren',
                request_serializer=nexus__pb2.GetChildrenRequest.SerializeToString,
                response_deserializer=nexus__pb2.GetChildrenResponse.FromString,
                _registered_method=True)


class NexusServiceServicer(object):
    """NexusService handles all publisher and consumer operations
    """

    def RegisterEventStream(self, request, context):
        """Publisher endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDatabaseTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Consumer endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Add this to the NexusService
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEventStream': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEventStream,
                    request_deserializer=nexus__pb2.RegisterEventStreamRequest.FromString,
                    response_serializer=nexus__pb2.RegisterEventStreamResponse.SerializeToString,
            ),
            'RegisterFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFile,
                    request_deserializer=nexus__pb2.RegisterFileRequest.FromString,
                    response_serializer=nexus__pb2.RegisterFileResponse.SerializeToString,
            ),
            'RegisterDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDirectory,
                    request_deserializer=nexus__pb2.RegisterDirectoryRequest.FromString,
                    response_serializer=nexus__pb2.RegisterDirectoryResponse.SerializeToString,
            ),
            'RegisterDatabaseTable': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDatabaseTable,
                    request_deserializer=nexus__pb2.RegisterDatabaseTableRequest.FromString,
                    response_serializer=nexus__pb2.RegisterDatabaseTableResponse.SerializeToString,
            ),
            'StoreValue': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreValue,
                    request_deserializer=nexus__pb2.StoreValueRequest.FromString,
                    response_serializer=nexus__pb2.StoreValueResponse.SerializeToString,
            ),
            'DeletePath': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePath,
                    request_deserializer=nexus__pb2.DeletePathRequest.FromString,
                    response_serializer=nexus__pb2.DeletePathResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=nexus__pb2.SubscribeRequest.FromString,
                    response_serializer=nexus__pb2.Event.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=nexus__pb2.GetPathRequest.FromString,
                    response_serializer=nexus__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=nexus__pb2.GetChildrenRequest.FromString,
                    response_serializer=nexus__pb2.GetChildrenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.NexusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.NexusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusService(object):
    """NexusService handles all publisher and consumer operations
    """

    @staticmethod
    def RegisterEventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/RegisterEventStream',
            nexus__pb2.RegisterEventStreamRequest.SerializeToString,
            nexus__pb2.RegisterEventStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/RegisterFile',
            nexus__pb2.RegisterFileRequest.SerializeToString,
            nexus__pb2.RegisterFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/RegisterDirectory',
            nexus__pb2.RegisterDirectoryRequest.SerializeToString,
            nexus__pb2.RegisterDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDatabaseTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/RegisterDatabaseTable',
            nexus__pb2.RegisterDatabaseTableRequest.SerializeToString,
            nexus__pb2.RegisterDatabaseTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/StoreValue',
            nexus__pb2.StoreValueRequest.SerializeToString,
            nexus__pb2.StoreValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/DeletePath',
            nexus__pb2.DeletePathRequest.SerializeToString,
            nexus__pb2.DeletePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nexus.NexusService/Subscribe',
            nexus__pb2.SubscribeRequest.SerializeToString,
            nexus__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/GetNode',
            nexus__pb2.GetPathRequest.SerializeToString,
            nexus__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusService/GetChildren',
            nexus__pb2.GetChildrenRequest.SerializeToString,
            nexus__pb2.GetChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
